name = "QuadraticTeamDecisionSolver"
uuid = "32b35200-ffec-42d1-a010-d82a751ad1c5"
authors = ["Santos Michelena"]
version = "1.0.0-DEV"

[deps]
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"

[compat]
julia = "1.9"
