name = "QuadraticTeamDecisionSolver"
uuid = "32b35200-ffec-42d1-a010-d82a751ad1c5"
authors = ["Santos Michelena"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
