name: Documentation

on:
  push:
    branches:
<<<<<<< HEAD
      - master # update to match your development branch (master, main, dev, trunk, ...)
=======
      - main # update to match your development branch (master, main, dev, trunk, ...)
>>>>>>> e23e9b6 (documentation workflow added)
    tags: '*'
  pull_request:

jobs:
  build:
    permissions:
      contents: write
      statuses: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: julia-actions/setup-julia@v1
        with:
<<<<<<< HEAD
          version: '1.6'
=======
          version: '1.9.2'
>>>>>>> e23e9b6 (documentation workflow added)
      - name: Install dependencies
        run: julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd())); Pkg.instantiate()'
      - name: Build and deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # If authenticating with GitHub Actions token
          DOCUMENTER_KEY: ${{ secrets.DOCUMENTER_KEY }} # If authenticating with SSH deploy key
        run: julia --project=docs/ docs/make.jl